---

- name: restart redis
  service: 
    name: "{{ redis_daemon }}"
    state: restarted

- name: rabbitmq restart
  service:
    name: rabbitmq-server
    state: restarted

- name: start rabbitmq app
  command: rabbitmqctl start_app