---

# Usage:
#    ansible-playbook ./play.yml -i ./inventory --ask-vault-pass -e 'ansible_user=<>'

- hosts: servers

  vars_files:
  - './vault.yml'

  become: yes
  become_user: root
  become_method: sudo
  any_errors_fatal: false
  max_fail_percentage: 0

  roles:
  - prepare_folder_structure
  - webhook
  - checkout_app
  - add_env_files
  - update_app
  - deploy_app

