- name: Ensure firewalld is installed
  package:
    name: firewalld
    state: latest

- name: Enable firewalld
  service:
    name: firewalld
    state: started
    enabled: yes

- name: Set dmz as default policy
  command: firewall-cmd --set-default-zone=public

- firewalld:
    zone: public
    service: http
    permanent: yes
    state: enabled

- firewalld:
    zone: public
    service: https
    permanent: yes
    state: enabled

- firewalld:
    zone: public
    service: ssh
    permanent: yes
    state: enabled

- firewalld:
    zone: internal
    service: ssh
    permanent: yes
    state: enabled

- name: Bounce firewalld
  service:
    name: firewalld
    state: restarted