- name: Ensure firewalld is installed
  package:
    name: firewalld
    state: latest

- name: Enable firewalld
  service:
    name: firewalld
    state: started
    enabled: yes

- name: Set dmz as default policy
  command: firewall-cmd --set-default-zone=public

- firewalld:
    zone: public
    service: http
    permanent: yes
    state: enabled

- firewalld:
    zone: public
    service: https
    permanent: yes
    state: enabled

- firewalld:
    zone: public
    service: ssh
    permanent: yes
    state: enabled

- name: Enable docker IPs internally (172.16.0.0)
  firewalld:
    rich_rule: rule family=ipv4 source address="172.16.0.0/16" accept
    zone: public
    permanent: yes
    immediate: yes
    state: enabled

- name: Enable docker IPs internally (172.17.0.0)
  firewalld:
    rich_rule: rule family=ipv4 source address="172.17.0.0/16" accept
    zone: public
    permanent: yes
    immediate: yes
    state: enabled

- name: Enable docker IPs internally (172.18.0.0)
  firewalld:
    rich_rule: rule family=ipv4 source address="172.18.0.0/16" accept
    zone: public
    permanent: yes
    immediate: yes
    state: enabled


- name: Enable docker IPs internally (172.19.0.0)
  firewalld:
    rich_rule: rule family=ipv4 source address="172.19.0.0/16" accept
    zone: public
    permanent: yes
    immediate: yes
    state: enabled
    
- name: Bounce firewalld
  service:
    name: firewalld
    state: restarted