---

- name: Install Git
  package:
    name: git
    state: latest

- name: Install python-pip
  package:
    name: python-pip
    state: latest

- name: Install ViM
  package:
    name: vim
    state: latest

- name: Install net-tools
  package:
    name: net-tools
    state: latest

- name: Install net-tools
  package:
    name: telnet
    state: latest
  

  