---

# Usage:
#    ansible-playbook ./play.yml -i ./inventory --ask-vault-pass -e 'ansible_user=<>'

- hosts: servers

  vars_files:
  - 'vault.yml'

  become: yes
  become_user: root
  become_method: sudo
  any_errors_fatal: false
  max_fail_percentage: 0

  roles:
  # - update_all
  - mssql-server
  - redis
  - docker
  - firewalld

