---
- name: install the package, force upgrade
  pip:
    name: pip
    extra_args: --upgrade

- name: Docker-compose fix
  pip:
    name: docker-compose
    state: latest

- name: Pull newer images
  shell: docker-compose -f "/home/{{ ansible_user }}/repos/judge-workers-deployment/judge-web/{{ application_environment }}/docker-compose.yml" pull