---
# Install Docker

- name: Install Docker dependencies
  package:
    name: "{{ packages }}"
    state: latest
  vars: 
    packages:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2 

- name: Configuring docker-ce repo
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
    mode: 0644

- name: Install Docker CE
  package:
    name: "{{ packages }}"
    state: latest
  vars: 
    packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io

- name: Enable the Docker daemon in systemd
  systemd:
    name: docker
    enabled: yes
    masked: no

- name: Start the Docker daemon
  systemd:
    name: docker
    state: started
    masked: no

- name: Check if Docker Compose is installed
  command: docker-compose --version
  register: docker_compose_check
  ignore_errors: yes

- shell: uname -s
  register: uname_s_result

- shell: uname -m
  register: uname_m_result

- name: Download and install Docker Compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/1.24.1/docker-compose-{{ uname_s_result.stdout }}-{{ uname_m_result.stdout }}"
    dest: /usr/bin/docker-compose
    mode: 0755
  when:
    - docker_compose_check.msg is defined
    - docker_compose_check.msg.find('No such file or directory') != -1

- name: Add user(s) to "docker" group
  user:
    name: "{{ ansible_user }}"
    groups: "docker"
    append: true
