---
# Install Docker

## Remove old packages

- name: Remove old Docker packages
  package:
    name: "{{ packages }}"
    state: absent
  vars: 
    packages:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc

## Install docker dependencies
- name: Install Docker dependencies
  package:
    name: "{{ packages }}"
    state: latest
  vars: 
    packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

## Add Docker-ce repository
- name: Add specified repository into sources list
  ansible.builtin.apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Update for Docker repo
  apt:
    update_cache: yes

# ## Update cache
# - name: Update apt-get repo and cache
#   apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

- name: Install Docker CE
  package:
    name: "{{ packages }}"
    state: latest
  vars: 
    packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io

- name: Enable the Docker daemon in systemd
  systemd:
    name: docker
    enabled: yes
    masked: no

- name: Start the Docker daemon
  systemd:
    name: docker
    state: started
    masked: no

- name: Check if Docker Compose is installed
  command: docker-compose --version
  register: docker_compose_check
  ignore_errors: yes

- shell: uname -s
  register: uname_s_result

- shell: uname -m
  register: uname_m_result

- name: Download and install Docker Compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-{{ uname_s_result.stdout }}-{{ uname_m_result.stdout }}"
    dest: /usr/bin/docker-compose
    mode: 0755
  when:
    - docker_compose_check.msg is defined
    - docker_compose_check.msg.find('No such file or directory') != -1

- name: Add user(s) to "docker" group
  user:
    name: "{{ ansible_user }}"
    groups: "docker"
    append: true
