--- 
- name: Create hooks directory
  file:
    path: "/home/{{ ansible_user }}/hooks"
    state: directory
    mode: '0777'

- name: Install webhook
  package:
    name: webhook
    state: present

- name: Add webhook configuration
  template:
    src: hooks.json.j2
    dest: "/home/{{ ansible_user }}/hooks/hooks.json"
    mode: '0777'