---
# Update all packages
- name: Upgrade all packages
  apt: upgrade=dist force_apt_get=yes
# - name: Update all packages
#   yum:
#     update_only: yes
#     state: latest

# - name: Install epel-release repository
#   apt:
#     name: epel-release
#     state: present
#     force_apt_get: true

# - name: Install IUS repository
#  yum_repository:
#    name: ius
#    file: ius
#    description: IUS Community Packages for Enterprise Linux 7 - $basearch
#    mirrorlist: https://mirrors.iuscommunity.org/mirrorlist?repo=ius-centos7&arch=$basearch&protocol=http
#    gpgkey: http://dl.iuscommunity.org/pub/ius/IUS-COMMUNITY-GPG-KEY
#    enabled: yes
#    gpgcheck: yes
  
# - name: Install WANDisco repository
#   yum_repository:
#     name: WANDisco
#     file: wandisco
#     description: WANDisco git repository
#     baseurl: http://opensource.wandisco.com/rhel/$releasever/git/$basearch
#     gpgkey: http://opensource.wandisco.com/RPM-GPG-KEY-WANdisco
#     enabled: yes
#     gpgcheck: yes

