---

# install mssql-server package

- name: install mssql-server repo (CentOS, RedHat)
  get_url:
    url: "{{ centos_server_repo_url }}"
    dest: /etc/yum.repos.d/mssql-server.repo
  when: ansible_distribution in ['CentOS', 'RedHat']

- name: install mssql-server repo (Ubuntu)
  get_url:
    url: "{{ ubuntu_server_repo_url }}"
    dest: /etc/apt/sources.list.d/mssql-server.list
  when: ansible_distribution == 'Ubuntu'

- name: refresh apt-get cache for server repo (Ubuntu)
  command: apt-get update
  when: ansible_distribution == 'Ubuntu'

- name: install mssql-server package
  package:
    name: mssql-server
    state: latest


# setup

- name: mssql-server setup
  mssql_conf:
    setup_sa_password: "{{ sa_password }}"
    setup_pid: "{{ pid }}"
    login_name: 'sa'
    login_password: "{{ sa_password }}"


# TSQL endpoint

- name: set TSQL endpoint port
  mssql_conf:
    name: network.tcpport
    value: "{{ tsql_endpoint_port }}"
    login_name: 'sa'
    login_password: "{{ sa_password }}"

# mssql-tools package

- name: install mssql-tools repo (CentOS, RedHat)
  get_url:
    url: "{{ centos_tools_repo_url }}"
    dest: /etc/yum.repos.d/mssql-tools.repo
  when: ansible_distribution in ['CentOS', 'RedHat']

- name: install mssql-tools repo (Ubuntu)
  get_url:
    url: "{{ ubuntu_tools_repo_url }}"
    dest: /etc/apt/sources.list.d/mssql-tools.list
  when: ansible_distribution == 'Ubuntu'

- name: refresh apt-get cache for tools repo (Ubuntu)
  command: apt-get update
  when: ansible_distribution == 'Ubuntu'

- name: install mssql-tools package
  package:
    name: mssql-tools
    state: latest
  environment:
    ACCEPT_EULA: 'y'


# Start mssql-server service

- name: start sqlservr
  service:
    name: mssql-server
    state: started
