Vagrant.configure(2) do |config|
  config.vm.box_check_update = false

  config.vm.provider "virtualbox" do |vb, override|
    vb.name = "ansible-server"
    vb.memory = "4096"
    vb.cpus = 4
    override.vm.box = "centos/7"
    override.vm.network "private_network", type: "dhcp"

    config.ssh.insert_key = false
    config.ssh.private_key_path = ["keys/vagrant_ssh", "~/.vagrant.d/insecure_private_key"]
    config.vm.provision "file", source: "keys/vagrant_ssh.pub", destination: "~/.ssh/authorized_keys"

    override.vm.network :forwarded_port, host: 14080, guest: 80
    override.vm.network :forwarded_port, host: 14443, guest: 443
  end
end
