Vagrant.configure(2) do |config|
  config.vm.box_check_update = false

  config.vm.provider "virtualbox" do |vb, override|
    vb.name = "apps-server"
    vb.memory = "4096"
    vb.cpus = 4
    # Do not use official Ubuntu box, broken in many ways https://bugs.launchpad.net/cloud-images/+bug/1569237
    override.vm.box = "centos/7"
    override.vm.network "private_network", type: "dhcp"
    override.vm.network :forwarded_port, host: 8001, guest: 8001
    override.vm.network :forwarded_port, host: 8002, guest: 8002
    override.vm.network :forwarded_port, host: 8003, guest: 8003
    override.vm.network :forwarded_port, host: 8004, guest: 8004
    override.vm.network :forwarded_port, host: 8005, guest: 8005
    override.vm.network :forwarded_port, host: 8006, guest: 8006
    override.vm.network :forwarded_port, host: 8007, guest: 8007
    override.vm.network :forwarded_port, host: 8008, guest: 8008
    override.vm.network :forwarded_port, host: 8009, guest: 8009
    override.vm.network :forwarded_port, host: 8010, guest: 8010
    override.vm.network :forwarded_port, host: 8011, guest: 8011
    override.vm.network :forwarded_port, host: 8020, guest: 8020
  end
  scripts = [ "bootstrap.sh" ]
  scripts.each { |script|
    config.vm.provision :shell, privileged: false, :path => "./" << script
  }
end